### ISSUE TITLE
The property and Cmds daemon

### ISSUE THREAD

**Issue by seikichin** [age-of-elements/age-of-elements#2]
How are you going to  deal with the property and the cmds.  are you going to separate cmds into different folders

**Comment by seikichin** [comment]
This is not an issue just communicate

**Comment by mpconley** [comment]
> This is not an issue just communicate

Inspired by this from Sticklib: https://github.com/kandawen/sticklib/tree/master/bin

**Comment by seikichin** [comment]
thank you
