### ISSUE TITLE
prompt 

### ISSUE THREAD

**Issue by seikichin** [age-of-elements/age-of-elements#3]
maybe the prompt problem is the lib it self not the driver or mudlet. I test Unitopia lib it supports mxp too when under utf-8 the prompt ">" is just ok won't become ";". when use age-of-elements lib ">" will become ";" maybe the aoe lib's mxp part doesn't handled properly

**Comment by mpconley** [comment]
We think this will be solved in a new version of Mudlet that they are reworking the MXP processing: https://github.com/Mudlet/Mudlet/issues/1623.  It should be available in a release after 4.8.

**Comment by seikichin** [comment]
that 's nice
